version: '3.7'

services:
  web:
    build: .
    restart: unless-stopped
    command: ./docker-web-postgres.sh
    volumes:
      - .:/MyExams
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    build: ./postgres_data
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres_data/data:/var/lib/postgresql/data/
volumes:
  postgres_data:
