# Generated by Django 3.0.4 on 2021-01-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('location', models.CharField(default='127.0.0.1:8000/api/v1', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.Exam')),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.Student')),
            ],
        ),
    ]
