# Generated by Django 3.0.4 on 2021-01-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20210109_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
