# Generated by Django 3.0.4 on 2021-01-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20210108_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('host', models.CharField(default='127.0.0.1', max_length=25)),
                ('bind_key', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='locations',
            field=models.ForeignKey(default='No Questions', on_delete=django.db.models.deletion.DO_NOTHING, to='exams.ExamLocation'),
        ),
    ]
