# Generated by Django 3.0.4 on 2021-01-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.Exam')),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.Student')),
            ],
        ),
    ]
