# Generated by Django 3.0.4 on 2021-01-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20210110_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='date_finish',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='date_start',
        ),
        migrations.AddField(
            model_name='exam',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(default='127.0.0.1:8000/api/exams/', max_length=250),
        ),
    ]
