# Generated by Django 3.0.4 on 2021-01-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20210109_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
    ]
