# Generated by Django 3.0.4 on 2021-01-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_exam_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.FileField(default='No Questions', upload_to='exam_questions'),
        ),
    ]
